# Generated by Django 2.2.1 on 2019-08-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
