# Generated by Django 2.2.1 on 2019-08-26 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_invoices', '0002_auto_20190826_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('Euros', 'Euros'), ('USD', 'USD'), ('Pounds', 'Pounds')], default='Euros', max_length=20)),
                ('date', models.DateField(auto_now=True)),
                ('item_code', models.CharField(max_length=10)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('unit_price', models.FloatField(default=0.0)),
                ('discount', models.FloatField(default=0.0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_invoices.Customer')),
                ('item_description', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products_invoices.Product')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
