# Generated by Django 2.2.1 on 2019-08-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_invoices', '0004_auto_20190826_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='discount',
            field=models.FloatField(),
        ),
    ]
