# Generated by Django 2.2.1 on 2019-08-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0002_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
